# Generated by Django 3.0.8 on 2020-08-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200721_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paratuscomment',
            name='paratus_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.ParatusPost'),
        ),
    ]
