# Generated by Django 3.0.8 on 2020-08-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200813_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paratuscomment',
            options={'ordering': ['created_at']},
        ),
    ]
